### ISSUE TITLE
Replace thumbnail images on news page first three articles

### ISSUE THREAD

**Issue by claredillon** [CURIOSSorg/curioss.org#38]
The green border is not showing up right for the thumbnails on the news page - can we replace with the following... the template for creating the images now includes the green border...

Here are the new images:
Jul 2024
![curioss-news-jul24-newgrant](https://github.com/user-attachments/assets/179560da-ad6e-4759-a9b9-55a22867ab20)

May 2024 
![curioss-news-may24-newmembers](https://github.com/user-attachments/assets/b722e8f2-f257-45b8-8510-5e31a530486c)

Sep 2023
![curioss-news-sep23-award](https://github.com/user-attachments/assets/1a7dafb9-ac7f-4cc2-81e2-a06766c4324f)

**Comment by RichardLitt** [comment]
@claredillon We can pretty easily do this in CSS, if that's easier?
