### ISSUE TITLE
Changing contact page until contact form is fixed

### ISSUE THREAD

**Issue by CiaraFlanagan** [CURIOSSorg/curioss.org#4]
Hi there @mmeagher11 

Further to our chat today, can you:

1. Remove the questions and contact fields on the contact CURIOSS webpage.
2. Replace the text: 'please fill in the form below. A member of the CURIOSS organizing team will be in contact.' with 'please email ciara.flanagan@curioss.org for more information.'

![image](https://github.com/CURIOSSorg/curioss.org/assets/101422261/ed6d00c2-440e-481d-9dab-3b19891af291)

**Comment by CiaraFlanagan** [comment]
Hi again @mmeagher11 

Can you change the contact email from ciara.flanagan@curioss.org to info@curioss.org please.

**Comment by mmeagher11** [comment]
Removed the following code and update the text "CURIOSS is a Community for University and Research Institution OSPOs. If you want to find out more about the CURIOSS community, please drop us an email @ [info@curioss.org](mailto:info@curioss.org). A member of the CURIOSS organizing team will be in contact."


<section class="section" style="padding-top: 20px; padding-bottom: 20px;">
  <div class="container">
   <div class="col-md-6">
    <div class="bg-white p-4">
          <form action="https://docs.google.com/forms/d/e/1FAIpQLSdhSsURaiS-molwKRlFPnvqncCx1Vd0BmRs0ATl75z5R2-YxA/formResponse" target="_blank" method="post">
            <input type="text" id="name" name="name" class="form-control mb-4 px-0" placeholder="Name" required>
            <input type="text" id="email" name="email" class="form-control mb-4 px-0" placeholder="Email address" required>
            <input type="text" id="organization" name="organization" class="form-control mb-4 px-0" placeholder="Institution or Organization" required>
            <label for="question">Please include your question here</label>
            <textarea id="question" name="question" rows="4" cols="50" required>
            </textarea>
            <label for="ospo_info">If applicable, please tell us a little about your institution's OSPO</label>
            <textarea id="ospo_info" name="ospo_info" rows="4" cols="50">
            </textarea>
            <input class="btn btn-primary" type="submit" value="Submit">
          </form>
    </div>
  </div>
</section>

**Comment by CiaraFlanagan** [comment]
Thanks for the fix @mmeagher11
